kind: Service
apiVersion: v1
metadata:
  name: javaapp
  namespace: default
spec:
  selector:
    app: javaapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8060
    nodePort: 30000
  type: NodePort
